# Generated by Django 5.1.2 on 2025-07-22 05:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='attendee_count',
            new_name='expected_attendees',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='approval_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='title',
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(default='Meeting', help_text='Meeting/event purpose or title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if booking was rejected'),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Special requirements or notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Booking approval status', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('catering', 'Catering'), ('equipment', 'Equipment'), ('supplies', 'Office Supplies'), ('decoration', 'Decoration'), ('transport', 'Transportation'), ('other', 'Other')], default='other', help_text='Type of procurement order', max_length=20)),
                ('items_description', models.TextField(help_text='Detailed description of items to be procured')),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost in local currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Order priority level', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Order processing status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Related booking', on_delete=django.db.models.deletion.CASCADE, related_name='procurement_orders', to='bookings.booking')),
                ('created_by', models.ForeignKey(help_text='User who created this order', on_delete=django.db.models.deletion.CASCADE, related_name='created_procurement_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procurement Order',
                'verbose_name_plural': 'Procurement Orders',
                'db_table': 'procurement_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
