# Generated by Django 5.0.7 on 2025-07-22 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name (e.g., "Conference Room A - Main Building")', max_length=255)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of people the room can accommodate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('category', models.CharField(choices=[('conference_room', 'Conference Room'), ('meeting_room', 'Meeting Room'), ('boardroom', 'Boardroom'), ('training_room', 'Training Room'), ('event_hall', 'Event Hall'), ('auditorium', 'Auditorium')], help_text='Type/category of the room', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Physical location of the room (building, floor, etc.)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the room')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of available amenities (projector, whiteboard, etc.)')),
                ('image', models.ImageField(blank=True, help_text='Room photo', null=True, upload_to='rooms/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the room is available for booking')),
                ('advance_booking_days', models.PositiveIntegerField(default=30, help_text='How many days in advance room can be booked')),
                ('min_booking_duration', models.PositiveIntegerField(default=1, help_text='Minimum booking duration in hours')),
                ('max_booking_duration', models.PositiveIntegerField(default=8, help_text='Maximum booking duration in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon code', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room Amenity',
                'verbose_name_plural': 'Room Amenities',
                'db_table': 'room_amenities',
                'ordering': ['name'],
            },
        ),
    ]
